"""
Request context management for structured logging.

This module provides a ContextVar-based mechanism for propagating
request-scoped identifiers (request_id, user_id) through the entire
async call stack without explicit parameter passing.

How it works:
    1. RequestLoggerMiddleware calls bind_request_context() at the start
       of each request, storing a LogContext in the current async task's
       context.
    2. The JSON log formatter calls get_log_context() on every log record
       to enrich the output with request_id and user_id.
    3. Because ContextVar is async-safe, each concurrent request has its
       own independent LogContext -- no cross-request contamination.

Why ContextVar, not threading.local():
    FastAPI runs on asyncio. Multiple coroutines execute on the same thread
    concurrently. threading.local() stores one value per thread -- concurrent
    requests on the same thread would share and overwrite each other's context.
    ContextVar stores one value per async Task -- each request gets its own
    isolated copy, regardless of how many requests share a thread.

Manual usage in tests:
    from app.logging.context import bind_request_context, clear_log_context
    token = bind_request_context(request_id="req_test", user_id="u_test")
    logger.info("this line will include request_id and user_id")
    clear_log_context(token)
"""

from contextvars import ContextVar, Token
from dataclasses import dataclass


@dataclass(frozen=True)
class LogContext:
    """
    Immutable request-scoped context carried through the async call stack.

    Attributes:
        request_id: Unique identifier for this HTTP request.
                    Format: "req_<12hex>". Generated by RequestLoggerMiddleware.
        user_id:    Tenant identifier. Set by TenantContextMiddleware (M9).
                    Defaults to "anonymous" until auth middleware runs.
    """

    request_id: str
    user_id: str


# The module-level ContextVar. One value per async Task.
_log_context: ContextVar[LogContext | None] = ContextVar(
    "_log_context",
    default=None,
)

# Sentinel returned when no context is bound.
_NO_CONTEXT = LogContext(request_id="no_request", user_id="anonymous")


def bind_request_context(
    request_id: str,
    user_id: str = "anonymous",
) -> "Token[LogContext | None]":
    """
    Bind a new LogContext to the current async task's context.

    Called by RequestLoggerMiddleware at the start of each request.

    Args:
        request_id: Unique request identifier.
        user_id:    Tenant identifier. Defaults to "anonymous".

    Returns:
        Token: Pass this to clear_log_context() when the request completes.
    """
    context = LogContext(request_id=request_id, user_id=user_id)
    return _log_context.set(context)


def update_user_id(user_id: str) -> "Token[LogContext | None]":
    """
    Update the user_id in the current request context.

    Called by TenantContextMiddleware (Module 9) after resolving the
    authenticated user from the X-User-Id header.

    Args:
        user_id: The validated tenant identifier.

    Returns:
        Token: Pass this to clear_log_context() to restore previous state.
    """
    current: LogContext = _log_context.get(_NO_CONTEXT) or _NO_CONTEXT
    updated = LogContext(
        request_id=current.request_id,
        user_id=user_id,
    )
    return _log_context.set(updated)


def clear_log_context(token: "Token[LogContext | None]") -> None:
    """
    Restore the context to its state before bind_request_context() was called.

    Called by RequestLoggerMiddleware in the finally block after each request.

    Args:
        token: The Token returned by bind_request_context() or update_user_id().
    """
    _log_context.reset(token)


def get_log_context() -> LogContext:
    """
    Return the current request's LogContext, or the no-context sentinel.

    Called by the JSON log formatter on every log record.

    Returns:
        LogContext: Current context, or _NO_CONTEXT outside a request lifecycle.
    """
    result = _log_context.get(None)
    if result is None:
        return _NO_CONTEXT
    return result
